name: doap-test

services:
  - name: webapp
    environment_slug: node-js
    instance_size_slug: basic-xxs
    github:
      repo: 0xsven/doap-test-mono
      branch: master
      deploy_on_push: true
    source_dir: webapp
    build_command: npm run build
    run_command: npm run start
    http_port: 3000
    routes:
      - path: /

  - name: api
    environment_slug: node-js
    instance_size_slug: basic-xxs
    github:
      repo: 0xsven/doap-test-mono
      branch: master
      deploy_on_push: true
    source_dir: api
    build_command: npm run build
    run_command: npm run start
    http_port: 4000
    routes:
      - path: /graphql
